project:
  type: website

execute:
  freeze: true

website:
  title: "Morteza Ansarinia"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css
